# Generated by Django 3.1 on 2020-08-17 03:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="Movie's title")),
                ('year', models.PositiveIntegerField(default=2019)),
                ('rated', models.CharField(max_length=64)),
                ('released_on', models.DateField(verbose_name='Release Date')),
                ('genre', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('plot', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('comment', models.CharField(default='', max_length=200)),
                ('movie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
    ]
